[package]
name = "ffi_example_for_lean"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
lean-sys = { version = "0.0.7", default-features = false, features = ["extern"] }

